name: CI/CD Pipeline for Wisecow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: <your-docker-image>:latest
          # Optionally, you can add a docker registry here (e.g., Docker Hub or GitHub Container Registry)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Kubernetes
        uses: azure/setup-kubernetes@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f k8s-deployment.yaml
